node ('master'){
def server = Artifactory.server "jfrog"
def buildInfo = Artifactory.newBuildInfo()

stage('Git-CheckOut') {
  git 'https://github.com/jyotiprasad06/devopsproject.git'
}
stage('Maven-Clean') {
    sh 'mvn clean'
}

stage('Maven-Compile') {
sh 'mvn compile'
}

stage('Maven-Test') {
sh 'mvn test'
}

stage('Maven-Package') {
sh 'mvn package'
}
server.upload spec: uploadSpec

stage('SonarQube') {
  withSonarQubeEnv('Sonar') {
    sh 'mvn sonar:sonar'
  }
}

stage('Build Management') {
   def uploadSpec = """{ 
     "files": [
        {
         "pattern": "**/*.war",
         "target": "generic-local"
        }
      ]

}"""

}

}
