node ('master'){


stage('Git-CheckOut') {
  git 'https://github.com/jyotiprasad06/devopsproject.git'
}
dir('petclinic-code') {
stage('Maven-Clean') {
    sh 'mvn clean'
}

stage('Maven-Compile') {
sh 'mvn compile'
}

stage('Maven-Test') {
sh 'mvn test'
}

stage('Maven-Package') {
sh 'mvn package'
}


stage('Archive-Artifacts') {
archiveArtifacts artifacts: 'target/*.war', followSymlinks: false
}
}
}
